services:
  villa73:
    container_name: villa73
    image: villa73
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - homeapp73-docker_default

networks:
  homeapp73-docker_default:
    external: true
