services:
  web:
    image: villa73-web
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - default
      - old_stack
  api:
    image: villa73-api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./cmd/api/Dockerfile
    ports:
      - 6001:6001
    networks:
      - default

networks:
  old_stack:
    external: true
    name: homeapp73-docker_default
